language: swift

cache:
  - bundler
  - cocoapods
osx_image: xcode8.1

git:
  depth: 3

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install cocoapods -v 1.2.0
  - gem install xcpretty -v 0.2.4
  - gem install xcpretty-travis-formatter
  - xcrun simctl list

install: true

env:
  - MODE=cocoapods-lint

script: ./build.sh $MODE

# whitelist
branches:
  only:
    - master
